### ISSUE TITLE
ERC3475data.sol is missing

### ISSUE THREAD

**Issue by victoryeo** [Debond-Protocol/EIP-3475#11]
Where is  'ERC3475data.sol'? It is mentioned in ReadMe, but it can not be found anywhere.

**Comment by GrandGarcon** [comment]
hi , thanks for checking  the issue . 

this was corresponding to the eip-3475 previous draft version implementation  , which has been edited and new version of the implementation is combined version with the internal storage of class and bonds withing the functions for issuing , redeeming and managing the lifecycle as explained in the contract here [here](https://github.com/Debond-Protocol/EIP-3475/tree/master/contracts).  

we will be updating the readme docs soon in order to reflect current progress.

**Comment by dr-chain** [comment]
@victoryeo I hope this solves your issue. Otherwise feel free to reopen it.
