### ISSUE TITLE
refactoring  governance contracts

### ISSUE THREAD

**Issue by yuliu-debond** [Debond-Protocol/EIP-3475#38]
- [x] all the staking functions should be in the staking contract.

- [x]  all the storage should be in the storage contract.

- [x] all the executable should be in the governance executable .

- [x] all the functions related to governance action should be in the governance contract.

**Comment by Edoumou** [comment]
@yuliu-debond could you define functions that you said related to Governance and that should be in the Governance contracts ?

- Should the function  **vote** that allows user to vote be in the Governance contract or in a contract that contains the voting logic as with staking ? I just remind that all protocols like Aave, Sushiswap, Uniswap, etc... have their **vote function** defined directly in the Governance contract, since **voting** is surely one of governance functionalities.

Here is some of the functions that you need to tell where they should be, for me they are all Governance functionalities and should be in the Governance contract. Can you check those you think should be in the Governance contract, and where the others should be in case they shouldn't be in Gov ? 

-[ ] CreateProposal
-[ ] CancelProposal
-[ ] ExecuteProposal
-[ ] Vote
-[ ] Redeem vote tokens rewards

**Comment by Edoumou** [comment]
- Refactoring Governance according to what was discussed last week **is over**

- Tests have been separated into categories. They all passed

What remains to do is to merge Cédric changes on **executables** into my branch which will become the **development branch** for **Governance**. Then those changes must be reviewed and approved before the branch can be merged into **main**
